### ISSUE TITLE
MadHacks logo should be unangled on the front page

### ISSUE THREAD

**Issue by LOZORD** [JoeDailey/MadHacks2015#3]
I think it would look less weird

**Comment by JoeDailey** [comment]
I dont think so

![screenshot from 2015-02-02 01 41 15](https://cloud.githubusercontent.com/assets/3579057/5997168/2a795ecc-aa7d-11e4-8a08-90806c840611.png)

**Comment by LOZORD** [comment]
Yeah, we can wait to see how it looks with the rest of the cosmetic changes
